apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    run: jenkins
spec:
  containers:
  - name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - containerPort: 8080
        name: agent
      - containerPort: 50000
        name: http

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    run: jenkins
  ports:
    - protocol: TCP
      port: 8080        # Port exposed by the service
      targetPort: 8080   # Port on the container
      name: agent       # Name for the service port
    - protocol: TCP
      port: 50000       # Port for agent communication
      targetPort: 50000 # Port on the container
      name: http        # Name for the service port
  type: NodePort        # Use NodePort to expose the service to external access
